### ISSUE TITLE
Builds 10 and 9

### ISSUE THREAD

**Issue by nicodt** [csimmonds/a4rpi-local-manifest#2]
First off thank you for the guide it is very straight forward and works like it advertises. 
Hi I have done two builds from the android 10 and the previous android 9 why would the android 9 be so extremely slow ? Do you have any ideas or tips for me to speed up the system to run smoother. The android 10 starts up and crashes back to the android boot logo as well . I am fairly new to android builds but have done a lot of kernel builds and tweaks .

**Comment by csimmonds** [comment]
The 9/Pie build is slower because it uses SwiftShader as the vendor OpenGL. The Q/10 build uses Mesa/DRM which is hardware accelerated.

I don't know why your Q/1- build is not launching. You have not given me enough information to help...
Cheers, Chris
