### ISSUE TITLE
ERROR DURING BUILDING ANDROID PIE 

### ISSUE THREAD

**Issue by sabakareem2997** [csimmonds/a4rpi-local-manifest#3]
I,am using a laptop installed with ubuntu 20.04LTS on virtual box .Code was succesfully downloaded and when i am trying to buid i am getting this error uploaded the image..it would be helpfulll if anyone help me out..
![Screenshot (28)](https://user-images.githubusercontent.com/68812424/106129343-2b9aa880-6186-11eb-93bc-ee07df7d7a0e.png)

**Comment by csimmonds** [comment]
I'm sorry that you have build errors. There is nothing in your screen shot that points to a specific cause. Usually in these situations I recommend double checking that everything has worked correctly up to this point. And then checking a third time. Then I would look for environmental issues - do you have enough memory (>> 16 GB), and storage space? Are the correct packages installed?

**Comment by sabakareem2997** [comment]
Thanks for your reply
