### ISSUE TITLE
Build failed - Metalava Check API

### ISSUE THREAD

**Issue by GanesanGuru** [csimmonds/a4rpi-local-manifest#4]
Dear sir,

I've got this error and I'm newbie to android builds. Let me know where I've made mistake.By the way, thanks for your elaborated guide.

[Error_log.docx](https://github.com/csimmonds/a4rpi-local-manifest/files/7033188/Error_log.docx)

[ 98% 68385/69377] //frameworks/base:api-stubs-docs Metalava Check API
FAILED: out/soong/.intermediates/frameworks/base/api-stubs-docs/android_common/check_last_released_api.timestamp out/soong/.intermediates/frameworks/base/api-stubs-docs/android_common/last_released_baseline.txt

******************************\nYou have tried to change the API from what has been previously released in\nan SDK.  Please fix the errors listed above.\n******************************\n" ; exit 38 )
Killed
-e 
******************************
You have tried to change the API from what has been previously released in
an SDK.  Please fix the errors listed above.
******************************

20:11:28 ninja failed with: exit status 1

#### failed to build some targets (03:55:33 (hh:mm:ss)) ####

**Comment by GanesanGuru** [comment]
Dear sir,

On re-build, it was successfully build sir. Maybe RAM might have run-off it sir. Anyway thanks.

**Comment by csimmonds** [comment]
This kind of error happens if you do not have enough RAM. You need 2 GB per core (or hardware thread), minimum 16 GB

However as you have seen, in most cases you can just run the build command again and it will succeed the second (or third or ...) time

**Comment by GanesanGuru** [comment]
Thanks for your information sir. The android 9/ Pie **Kernel Build** has failed with an error as stated below,while running this part of line.

**make -j $(nproc) zImage**
./scripts/gcc-version.sh: line 26: arm-linux-gnueabihf-gcc: command not found
./scripts/gcc-version.sh: line 27: arm-linux-gnueabihf-gcc: command not found
make: arm-linux-gnueabihf-gcc: Command not found
make: arm-linux-gnueabihf-gcc: Command not found
make: arm-linux-gnueabihf-gcc: Command not found
  CHK     include/config/kernel.release
make: arm-linux-gnueabihf-gcc: Command not found
Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
make: *** [Makefile:1190: prepare-compiler-check] Error 1
make: *** Waiting for unfinished jobs....

#### failed to build some targets  ####

Also I'm wondering in your Android 10 build was very slow in RPi3 model, hence I thought to using prior version of Android/your build Pie. Also, in another issue you have stated that Android 9 uses SwiftShader as the vendor OpenGLusing and I too would be slow. Then is there any possibility to switch that to Mesa itself?

Awaiting for your response sir.
